// Code generated by go2go; DO NOT EDIT.


//line iter.go2:1
package main

//line iter.go2:1
import (
//line iter.go2:1
 "bufio"
//line iter.go2:1
 "fmt"
//line iter.go2:1
 "io"
//line iter.go2:1
 "strconv"
//line iter.go2:1
 "strings"
//line iter.go2:1
)

//line iter.go2:42
func Lines(r io.Reader) instantiate୦୦Iter୦string {
	return linesIter{
		scanner: bufio.NewScanner(r),
	}
}

type linesIter struct {
	scanner *bufio.Scanner
}

func (i linesIter) Next() bool {
	return i.scanner.Scan()
}

func (i linesIter) Err() error {
	return i.scanner.Err()
}

func (i linesIter) Item() string {
	return i.scanner.Text()
}

//line iter.go2:62
type instantiate୦୦Iter୦string interface {
//line iter.go2:8
 Next() bool
			Item() string
			Err() error
}
//line iter.go2:11
type Importable୦ int

//line iter.go2:11
var _ = bufio.ErrAdvanceTooFar
//line iter.go2:11
var _ = fmt.Errorf

//line iter.go2:11
type _ io.ByteReader

//line iter.go2:11
var _ = strconv.AppendBool

//line iter.go2:11
type _ strings.Builder
