// Code generated by go2go; DO NOT EDIT.


//line bulk.go2:6
package batch

//line bulk.go2:6
import (
//line bulk.go2:6
 "fmt"
//line bulk.go2:6
 "log"
//line bulk.go2:6
 "sync"
//line bulk.go2:6
 "testing"
//line bulk.go2:6
 "time"
//line bulk.go2:6
)

//line bulk.go2:6
type Importable୦ int

//line bulk.go2:6
var _ = fmt.Errorf
//line bulk.go2:6
var _ = log.Fatal

//line bulk.go2:6
type _ sync.Cond

//line bulk.go2:6
var _ = testing.AllocsPerRun

//line bulk.go2:6
const _ = time.ANSIC
