// Code generated by go2go; DO NOT EDIT.


//line io.go2:13
package genericio

//line io.go2:13
import (
//line io.go2:13
 "bytes"
//line io.go2:13
 "crypto/sha1"
//line io.go2:13
 "errors"
//line io.go2:13
 "fmt"
//line io.go2:13
 "io"
//line io.go2:13
 "io/ioutil"
//line io.go2:13
 "runtime"
//line io.go2:13
 "sort"
//line io.go2:13
 "strings"
//line io.go2:13
 "sync"
//line io.go2:13
 "testing"
//line io.go2:13
 "time"
//line io.go2:13
)

//line io.go2:21
const (
	SeekStart   = 0
	SeekCurrent = 1
	SeekEnd     = 2
)

//line io.go2:29
var ErrShortWrite = errors.New("short write")

//line io.go2:32
var ErrShortBuffer = errors.New("short buffer")

//line io.go2:39
var EOF = io.EOF

//line io.go2:43
var ErrUnexpectedEOF = io.ErrUnexpectedEOF

//line io.go2:48
var ErrNoProgress = io.ErrNoProgress

//line io.go2:99
type Closer interface {
	Close() error
}

//line io.go2:116
type Seeker interface {
	Seek(offset int64, whence int) (int64, error)
}

//line io.go2:452
var errWhence = errors.New("Seek: invalid whence")
var errOffset = errors.New("Seek: invalid offset")

//line io.go2:453
type Importable୦ int
//line io.go2:453
type _ bytes.Buffer

//line io.go2:453
const _ = sha1.BlockSize

//line io.go2:453
var _ = errors.As
//line io.go2:453
var _ = fmt.Errorf

//line io.go2:453
type _ io.ByteReader

//line io.go2:453
var _ = ioutil.Discard
//line io.go2:453
var _ = runtime.BlockProfile

//line io.go2:453
type _ sort.Float64Slice
//line io.go2:453
type _ strings.Builder
//line io.go2:453
type _ sync.Cond

//line io.go2:453
var _ = testing.AllocsPerRun

//line io.go2:453
const _ = time.ANSIC
