// Code generated by go2go; DO NOT EDIT.


//line multi.go2:5
package genericio

//line multi.go2:5
import (
//line multi.go2:5
 "bytes"
//line multi.go2:5
 "crypto/sha1"
//line multi.go2:5
 "errors"
//line multi.go2:5
 "fmt"
//line multi.go2:5
 "io"
//line multi.go2:5
 "io/ioutil"
//line multi.go2:5
 "runtime"
//line multi.go2:5
 "sort"
//line multi.go2:5
 "strings"
//line multi.go2:5
 "sync"
//line multi.go2:5
 "testing"
//line multi.go2:5
 "time"
//line multi.go2:5
)

//line multi.go2:5
type _ bytes.Buffer

//line multi.go2:5
const _ = sha1.BlockSize

//line multi.go2:5
var _ = errors.As
//line multi.go2:5
var _ = fmt.Errorf

//line multi.go2:5
type _ io.ByteReader

//line multi.go2:5
var _ = ioutil.Discard
//line multi.go2:5
var _ = runtime.BlockProfile

//line multi.go2:5
type _ sort.Float64Slice
//line multi.go2:5
type _ strings.Builder
//line multi.go2:5
type _ sync.Cond

//line multi.go2:5
var _ = testing.AllocsPerRun

//line multi.go2:5
const _ = time.ANSIC
