// Code generated by go2go; DO NOT EDIT.


//line loadptr.go2:1
package atomic

//line loadptr.go2:1
import (
//line loadptr.go2:1
 "sync/atomic"
//line loadptr.go2:1
 "testing"
//line loadptr.go2:1
 "unsafe"
//line loadptr.go2:1
)

//line loadptr.go2:1
type Importable୦ int

//line loadptr.go2:1
var _ = atomic.AddInt32
//line loadptr.go2:1
var _ = testing.AllocsPerRun

//line loadptr.go2:1
type _ unsafe.Pointer
