// Code generated by tuple/generate.go. DO NOT EDIT.
package tuple

// T0 holds a tuple of 0 values.
type T0 = struct{}

// There is no 1-tuple - a 1-tuple is represented by the type itself.

// T2 holds a tuple of 2 values.
type T2[A0, A1 any] struct {
	A0 A0
	A1 A1
}

// T returns all the tuple's values.
func (t T2[A0, A1]) T() (A0, A1) {
	return t.A0, t.A1
}

// MkT2 returns a 2-tuple formed from its arguments.
func MkT2[A0, A1 any](a0 A0, a1 A1) T2[A0, A1] {
	return T2[A0, A1]{a0, a1}
}

// T3 holds a tuple of 3 values.
type T3[A0, A1, A2 any] struct {
	A0 A0
	A1 A1
	A2 A2
}

// T returns all the tuple's values.
func (t T3[A0, A1, A2]) T() (A0, A1, A2) {
	return t.A0, t.A1, t.A2
}

// MkT3 returns a 3-tuple formed from its arguments.
func MkT3[A0, A1, A2 any](a0 A0, a1 A1, a2 A2) T3[A0, A1, A2] {
	return T3[A0, A1, A2]{a0, a1, a2}
}

// T4 holds a tuple of 4 values.
type T4[A0, A1, A2, A3 any] struct {
	A0 A0
	A1 A1
	A2 A2
	A3 A3
}

// T returns all the tuple's values.
func (t T4[A0, A1, A2, A3]) T() (A0, A1, A2, A3) {
	return t.A0, t.A1, t.A2, t.A3
}

// MkT4 returns a 4-tuple formed from its arguments.
func MkT4[A0, A1, A2, A3 any](a0 A0, a1 A1, a2 A2, a3 A3) T4[A0, A1, A2, A3] {
	return T4[A0, A1, A2, A3]{a0, a1, a2, a3}
}

// T5 holds a tuple of 5 values.
type T5[A0, A1, A2, A3, A4 any] struct {
	A0 A0
	A1 A1
	A2 A2
	A3 A3
	A4 A4
}

// T returns all the tuple's values.
func (t T5[A0, A1, A2, A3, A4]) T() (A0, A1, A2, A3, A4) {
	return t.A0, t.A1, t.A2, t.A3, t.A4
}

// MkT5 returns a 5-tuple formed from its arguments.
func MkT5[A0, A1, A2, A3, A4 any](a0 A0, a1 A1, a2 A2, a3 A3, a4 A4) T5[A0, A1, A2, A3, A4] {
	return T5[A0, A1, A2, A3, A4]{a0, a1, a2, a3, a4}
}

// T6 holds a tuple of 6 values.
type T6[A0, A1, A2, A3, A4, A5 any] struct {
	A0 A0
	A1 A1
	A2 A2
	A3 A3
	A4 A4
	A5 A5
}

// T returns all the tuple's values.
func (t T6[A0, A1, A2, A3, A4, A5]) T() (A0, A1, A2, A3, A4, A5) {
	return t.A0, t.A1, t.A2, t.A3, t.A4, t.A5
}

// MkT6 returns a 6-tuple formed from its arguments.
func MkT6[A0, A1, A2, A3, A4, A5 any](a0 A0, a1 A1, a2 A2, a3 A3, a4 A4, a5 A5) T6[A0, A1, A2, A3, A4, A5] {
	return T6[A0, A1, A2, A3, A4, A5]{a0, a1, a2, a3, a4, a5}
}
